# Generated by Django 4.1.2 on 2022-10-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentprice',
            old_name='price_2_4_day',
            new_name='price_2_to_4_days',
        ),
        migrations.RenameField(
            model_name='equipmentprice',
            old_name='price_5_7_day',
            new_name='price_5_to_7_days',
        ),
        migrations.RenameField(
            model_name='equipmentprice',
            old_name='price_8_and_more_day',
            new_name='price_8_and_more_days',
        ),
    ]
