# Generated by Django 4.1.2 on 2022-10-05 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_2_4_day_equipmentprice_price_2_to_4_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='location',
            field=models.CharField(default='KTM', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='tenure',
            field=models.CharField(default='Oct 12 2022 - Dec 01 2022', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipmentprice',
            name='equipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='store.equipment'),
        ),
    ]
