# Generated by Django 4.1.2 on 2022-10-31 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_billinginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing_info', to='store.order'),
        ),
    ]
