# Generated by Django 4.1.2 on 2022-10-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_side_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='side_note',
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='side_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
